/**
 * Repair ticket type as defined in SYSTEM_RULES.md §RepairTicket.
 * REPAIR — created by users to report machine issues.
 * MAINTENANCE — auto-generated by the system from a MaintenanceSchedule.
 */
export const TicketType = {
  REPAIR: "REPAIR",
  MAINTENANCE: "MAINTENANCE",
} as const;

export type TicketTypeType = (typeof TicketType)[keyof typeof TicketType];

/**
 * All ticket type values as an array — useful for Mongoose enum validation.
 */
export const ALL_TICKET_TYPES = Object.values(TicketType) as [
  TicketTypeType,
  ...TicketTypeType[],
];
